---
database_file: "/home/vagrant/timetrap/timetrap.db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "/home/vagrant/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/vagrant/.timetrap/auto_sheets"
default_command: 
auto_checkout: true
require_note: true 
