---


    - name: vim installieren
      apt: name=vim

    - name: create vim config folder
      file: path="{{ user_home }}/.vim/autoload" state=directory
      become: yes
      become_user: "{{ user }}"

    - name: Plug installieren
      get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest="{{ user_home }}/.vim/autoload/plug.vim"
      become: yes
      become_user: "{{ user }}"
